Clean up run-podman

diff --git a/run-podman b/run-podman
--- a/run-podman
+++ b/run-podman
@@ -1,6 +1,4 @@
 #!/bin/bash
-#set -euox
-
 SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
 
 # Set variables
@@ -18,74 +16,32 @@ else
   CONTAINERFILE_PATH="$SCRIPT_DIR/Dockerfile.amd64"
 fi
 
-# MORE OPTIONS
-use_graphics=true
-
-# Check if container runtime exists
-check_container_runtime() {
-  if command -v "$CONTAINER_RUNTIME" >/dev/null; then
-    return 0
-  fi
-
-  echo "Container runtime '$CONTAINER_RUNTIME' not found"
-  echo "Runtimes detected:"
-  echo "  Podman: $(command -v podman >/dev/null && echo YES || echo NO)"
-  echo "  Docker: $(command -v docker >/dev/null && echo YES || echo NO)"
-
-  while true; do
-    read -p "Which container runtime? (podman/docker): " runtime
-    if [[ $runtime == podman ]]; then
-      CONTAINER_RUNTIME=podman
-      echo "Using podman as container runtime."
-      break
-    elif [[ $runtime = docker ]]; then
-      CONTAINER_RUNTIME=docker
-      echo "Using docker as container runtime."
-      break
-    else
-      echo "Invalid choice. Please enter 'podman' or 'docker'."
-    fi
-  done
-
-  echo ""
-}
-
 # NETWORK
-# Check if network exists
 has_network() {
-  podman network inspect "$NETWORK_NAME" &>/dev/null
+  "$CONTAINER_RUNTIME" network inspect "$NETWORK_NAME" &>/dev/null
 }
 
-# Create network
 create_network() {
   if has_network; then
-    echo "Network '$NETWORK_NAME' already exists. Skipping build."
+    echo "Network '$NETWORK_NAME' exists. Skipping build."
   else
     echo "Creating container-local network '$NETWORK_NAME'..."
-    podman network create "$NETWORK_NAME"
+    "$CONTAINER_RUNTIME" network create "$NETWORK_NAME"
   fi
 }
 
 # XHOST
 # Add host name to allowed connections on X server
 # do_xhost <host name>
-xhost_warned=false
 do_xhost() {
-  arg=$@
-
   if $(which xhost); then
     xhost $@
   else
-    if ! $xhost_warned; then
-      echo "Warning: xhost was not detected on your system. You may have issues running graphical apps like QEMU or Wireshark."
-      xhost_warned=true
-    fi
+    echo "Warning: xhost was not detected on your system. You may have issues running graphical apps like QEMU or Wireshark."
   fi
 }
 
-# Set up xhost
 setup_xhost() {
-  # OS-specific handling for X11 forwarding
   if test "$(uname)" = Linux; then
     if grep -qi Microsoft /proc/version; then # Windows
       true                                    # Nothing to do, configured in GUI outside WSL
@@ -103,32 +59,31 @@ setup_xhost() {
 }
 
 # IMAGE MANAGEMENT
-# Check if image exists
 has_image() {
-  podman image exists "$IMAGE_NAME" &>/dev/null
+  "$CONTAINER_RUNTIME" image exists "$IMAGE_NAME" &>/dev/null
 }
 
-# Build the image
 build_image() {
   if has_image; then
     echo "Image '$IMAGE_NAME' already exists. Skipping build."
     return 0
   fi
 
-  echo "Building Podman image '$IMAGE_NAME' for $PLATFORM..."
-  podman build -t "$IMAGE_NAME" -f "$CONTAINERFILE_PATH" --platform "${PLATFORM}" .
+  echo "Building "$CONTAINER_RUNTIME" image '$IMAGE_NAME' for $PLATFORM..."
+  echo_and_run "$CONTAINER_RUNTIME" build -t "$IMAGE_NAME" -f "$CONTAINERFILE_PATH" --platform "${PLATFORM}" .
+  if [[ $? -ne 0 ]]; then exit 1; fi
 }
 
 # Remove the image
 remove_image() {
   echo "Removing image '$IMAGE_NAME'..."
-  podman image rm --force "$IMAGE_NAME"
+  echo_and_run "$CONTAINER_RUNTIME" image rm --force "$IMAGE_NAME"
 }
 
 # CONTAINER MANAGEMENT
 # Check if container exists
 has_container() {
-  podman container exists "$CONTAINER_NAME" &>/dev/null
+  "$CONTAINER_RUNTIME" container exists "$CONTAINER_NAME" &>/dev/null
 }
 
 # Start a new container
@@ -181,7 +136,7 @@ start_new_container() {
 
   # Create the container
   echo "Creating and starting container '$CONTAINER_NAME'..."
-  podman run -it \
+  echo_and_run "$CONTAINER_RUNTIME" run -it \
     --name "$CONTAINER_NAME" \
     --platform "$PLATFORM" \
     --network "${NETWORK_NAME}" \
@@ -197,17 +152,19 @@ start_new_container() {
     $netarg \
     $x11arg $x11envarg \
     "$IMAGE_NAME"
+
+  if [[ $? -ne 0 ]]; then exit 1; fi
 }
 
 # Start or attach to an existing container
 start_container() {
-  STATUS=$(podman inspect -f '{{.State.Status}}' "$CONTAINER_NAME")
+  STATUS=$("$CONTAINER_RUNTIME" inspect -f '{{.State.Status}}' "$CONTAINER_NAME")
   if [[ "$STATUS" == "running" ]]; then
     echo "Container '$CONTAINER_NAME' is already running. Attaching..."
-    podman exec -it "$CONTAINER_NAME" bash
+    echo_and_run "$CONTAINER_RUNTIME" exec -it "$CONTAINER_NAME" bash
   else
     echo "Container '$CONTAINER_NAME' exists but is not running. Starting..."
-    podman start -ai "$CONTAINER_NAME"
+    echo_and_run "$CONTAINER_RUNTIME" start -ai "$CONTAINER_NAME"
   fi
 }
 
@@ -225,7 +182,25 @@ remove_containers() {
   local _name
   _name="${1:-${CONTAINER_NAME}}"
   echo "Removing all existing '$CONTAINER_NAME' containers..."
-  podman ps -a -f name=${_name} --format "{{.ID}}" | while read line; do podman rm --force $line; done
+  "$CONTAINER_RUNTIME" ps -a -f name=${_name} --format "{{.ID}}" | while read line; do echo_and_run "$CONTAINER_RUNTIME" rm --force $line; done
+}
+
+# Printing utilities
+
+RED='\033[31m'
+GREEN='\033[32m'
+BLUE='\033[0;34m'
+YELLOW='\033[33m'
+RESET='\033[0m'
+
+echo_and_run() {
+  echo -e "${BLUE}$*${RESET}"
+  "$@"
+}
+
+echo_error() {
+  local text="$1"
+  echo -e "${RED}${text}${RESET}"
 }
 
 # Show the help screen
@@ -257,9 +232,38 @@ info() {
   echo ""
 
   echo "Has runtime?" $(echo YES)
-  echo "Built image? $(has_image && echo YES || echo NO)"
-  echo "Set up container? $(has_container && echo YES || echo NO)"
-  echo "Created network? $(has_network && echo YES || echo NO)"
+  echo "Built image? $(has_image && echo YES || echo_error NO)"
+  echo "Set up container? $(has_container && echo YES || echo_error NO)"
+  echo "Created network? $(has_network && echo YES || echo_error NO)"
+  echo ""
+}
+
+# Check if container runtime exists
+check_container_runtime() {
+  if command -v "$CONTAINER_RUNTIME" >/dev/null; then
+    return 0
+  fi
+
+  echo "Container runtime '$CONTAINER_RUNTIME' not found"
+  echo "Runtimes detected:"
+  echo "  Podman: $(command -v "$CONTAINER_RUNTIME" >/dev/null && echo YES || echo NO)"
+  echo "  Docker: $(command -v docker >/dev/null && echo YES || echo NO)"
+
+  while true; do
+    read -p "Which container runtime? (podman/docker): " runtime
+    if [[ $runtime == "$CONTAINER_RUNTIME" ]]; then
+      CONTAINER_RUNTIME=podman
+      echo "Using podman as container runtime"
+      break
+    elif [[ $runtime = docker ]]; then
+      CONTAINER_RUNTIME=docker
+      echo "Using docker as container runtime"
+      break
+    else
+      echo "Invalid choice. Please enter 'podman' or 'docker'"
+    fi
+  done
+
   echo ""
 }
 
